version: '3.4'

services:
  sudo:
    image: sudo
    build:
      context: node_modules/sudo
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "lib/sudo.js"]
