apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendv2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontendv2
  template:
    metadata:
      labels:
        app: frontendv2
    spec:
      containers:
      - name: frontendv2
        image: alepellereca/imagenfront:2
        ports:
        - containerPort: 62383
---
apiVersion: v1
kind: Service
metadata:
  name: frontendservice
  spec:
    type: NodePort
    ports:
    - port: 2376
      targetPort: 62383
    selector:
      app: frontend

