apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendv2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backendv2
  template:
    metadata:
      labels:
        app: backendv2
    spec:
      containers:
      - name: backendv2
        image: alepellereca/imagenback:2
        ports:
        - containerPort: 62383
---
apiVersion: v1
kind: Service
metadata:
  name: backendservicev2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 62383
  selector:
    app: backend
