apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /frontendv1
        pathType: Prefix
        backend:
          service:
            name: frontendservice
            port:
              number: 80
      - path: /frontendv2
        pathType: Prefix
        backend:
          service:
            name: frontendservice
            port:
              number: 80
      - path: /backendv1
        pathType: Prefix
        backend:
          service:
            name: backendservice
            port:
              number: 80
      - path: /backendv2
        pathType: Prefix
        backend:
          service:
            name: backendservice
            port:
              number: 80
